name: Tiller
version: 1.0
description: Automatically replants crops when harvested with specific tools.
main: org.tiller.Tiller
api-version: '1.21'
folia-supported: true
authors: [ Vyladence ]

commands:
  tiller:
    description: 'Main command for the Tiller plugin'
    usage: /<command> <subcommand>
    permission: tiller.use
    aliases: [ar]
    subcommands:
      toggle:
        description: 'Toggle tiller feature'
        usage: /tiller toggle
        permission: tiller.use
      reload:
        description: 'Reload the Tiller plugin configuration'
        usage: /tiller reload
        permission: tiller.reload

permissions:
  tiller.use:
    description: Allows auto-replant and use of the tiller command
    default: op
  tiller.ignore_tool_restrictions:
    description: Allows ignoring tool restrictions for tiller
    default: false
  tiller.bypass_item_durability:
    description: Players with this permission will not lose durability on their tools when harvesting crops
    default: false
  tiller.command.reload:
    description: Allows reloading the plugin's config
    default: op